site_name: Mana
nav:
    - Introduction: 
        - Overview: 'Introduction/Overview.md'
        # - แนะนำ sandbox: 'Introduction/RecommendSandbox.md'
    - Quickstarts:
        - GettingStarted: 
            - ขั้นตอนการสมัครร่วมงานกับมานะ: 'Quickstarts/GettingStarted.md'
            - login เข้า apiM: 'Quickstarts/step_loginApiM.md'
        - APIS : 'Quickstarts/APIs.md'
    - Tutorial:
        - Using Adhoc: Tutorial/Adhoc.md
        - Environments: Tutorial/Environments.md
        - From Sandbox to Production: Tutorial/FromSandbox2Production.md
    - Plan & Pricing: 'Plan&Pricing/Plan&Pricing.md'
    - FAQ: 'FAQ/faq.md'
theme: readthedocs

