site_name: Mana
nav:
    - Introduction: 
        - Overview: 'Introduction/Overview.md'
        - แนะนำ sandbox: 'Introduction/RecommendSandbox.md'
    - Quickstarts:
        - GettingStarted: 
            - ขั้นตอนการสมัครร่วมงานกับมานะ: 'Quickstarts/GettingStarted.md'
            - login เข้า apiM: 'Quickstarts/step_loginApiM.md'
    - Tutorial:
        - Using Adhoc: Tutorial/Adhoc.md
        - Environments: Tutorial/Environments.md
    - Plan & Pricing:
        - ddd1: 'index.md'
        - ddd2: 'index.md'
    - FAQ:
        - eee1: 'index.md'
        - eee2: 'index.md'
theme: readthedocs

