site_name: Mana
nav:
    - INTRODUCTION: 
        - Overview: 'Introduction/Overview.md'
        - Development life cycle: 'Introduction/DevelopmentCycle.md'
        - Environments: Introduction/Environments.md
    - QUICKSTARTS: 
        - GettingStarted: Quickstarts/GettingStarted.md
            # - ขั้นตอนการสมัครร่วมงานกับมานะ: 'Quickstarts/GettingStarted.md'
            # - การเข้าใช้งาน DevPortal: 'Quickstarts/step_loginApiM.md'
    - TUTORIAL: 
        - Using Adhoc: Tutorial/Adhoc.md
        - From Sandbox to Production: Tutorial/FromSandbox2Production.md
    - APIs: 
        - About APIs: APIs/APIs.md
    - HOWTO: 
        - From Sandbox to Production: Howto/FromSandbox_Production.md
    - PLAN & PRICING: 
        - Plan & Pricing: Plan&Pricing/Plan&Pricing.md
    - FAQ:
        - ถาม-ตอบ: FAQ/faq.md
extra_css:
    - css/extra.css
theme:
    name: readthedocs
    favicon: 'img/favicon.ico'